/** Weapon definitions — keep in sync with backend/game/weapons.js */
export const WEAPON_TYPES = {
  swift_blade: {
    id: "swift_blade",
    name: "Swift Blade",
    nameVi: "Kiếm Tốc",
    icon: "⚡",
    color: "#22d3ee",
    glowBlur: 18,
    sparkCount: 7,
    damageMult: 1.08,
    wordTimer: true,
    description: "Từ ngắn có đếm giờ — thời gian dài hơn, sát thương nhẹ tăng.",
    tag: "Timer+",
    ultimateName: "Storm Cut",
    ultimatePhrase: "blade of the storm cuts deep",
    ultimateEffect: "Bão kiếm + 12 nhát chém boss (20/nhát) + finale xẻ màn hình",
  },
  shortsword: {
    id: "shortsword",
    name: "Shortsword",
    nameVi: "Kiếm Ngắn",
    icon: "🗡",
    color: "#94a3b8",
    glowBlur: 12,
    sparkCount: 5,
    damageMult: 0.68,
    description: "Từ dễ, nhịp bình thường — sát thương thấp.",
    tag: "Balanced",
    ultimateName: "Guardian Strike",
    ultimatePhrase: "honor guards the fallen line",
    ultimateEffect: "8 kiếm lao vào + xẻ màn hình bạc hoành tráng.",
  },
  greatsword: {
    id: "greatsword",
    name: "Greatsword",
    nameVi: "Đại Kiếm",
    icon: "⚔",
    color: "#f97316",
    glowBlur: 22,
    sparkCount: 6,
    damageMult: 1.55,
    description: "Từ dài, khó — sát thương rất cao.",
    tag: "Heavy",
    ultimateName: "Earth Splitter",
    ultimatePhrase: "the earth splits before my steel",
    ultimateEffect: "Đại kiếm rơi xuống — xẻ đất, sóng xung kích.",
  },
  lifestaff: {
    id: "lifestaff",
    name: "Life Staff",
    nameVi: "Gậy Hồi",
    icon: "💚",
    color: "#4ade80",
    glowBlur: 16,
    sparkCount: 6,
    damageMult: 0.88,
    healOnWord: 7,
    description: "Mỗi từ gõ xong hồi máu đội.",
    tag: "Heal",
    ultimateName: "Bloom of Life",
    ultimatePhrase: "life blooms where shadows fall",
    ultimateEffect: "Gậy khổng lồ đập xuống + sóng hồi + nở hoa hướng boss.",
  },
  fury_axe: {
    id: "fury_axe",
    name: "Fury Axe",
    nameVi: "Rìu Cuồng",
    icon: "🔥",
    color: "#ef4444",
    glowBlur: 14,
    sparkCount: 8,
    damageMult: 0.92,
    streakDamage: true,
    description: "Chuỗi gõ liên tục tăng sát thương.",
    tag: "Streak DMG",
    ultimateName: "Consuming Rage",
    ultimatePhrase: "rage consumes all who stand near",
    ultimateEffect: "Cột lửa + rìu khổng lồ quật xuống + xẻ màn đỏ.",
  },
  animous_codex: {
    id: "animous_codex",
    name: "Animous Codex",
    nameVi: "Thiên Ma Lục",
    icon: "📖",
    color: "#a78bfa",
    glowBlur: 20,
    sparkCount: 6,
    damageMult: 1.0,
    bookWeapon: true,
    description: "Chọn Thiện hoặc Ác để biến hình. Thánh miễn đòn; Quỷ sát thương cao.",
    tag: "Dual",
    ultimateName: "Sanctuary / Cataclysm",
    ultimatePhrase: "sanctuary psalm shields the faithful",
  },
  gatling_gun: {
    id: "gatling_gun",
    name: "Gatling Gun",
    nameVi: "Súng Mãng",
    icon: "🔫",
    color: "#eab308",
    glowBlur: 14,
    sparkCount: 10,
    damageMult: 0.42,
    gatlingMode: true,
    description: "Gõ 1 chữ cái trên bảng → 1 viên đạn. Sát thương cực thấp, bắn cực nhanh.",
    tag: "1-Key",
    ultimateName: "Lead Storm",
    ultimatePhrase: "lead storm falls upon the dark throne",
    ultimateEffect: "Ngắm boss + mưa 56 viên + finale nổ đạn.",
  },
};

export const RAGE_MAX = 100;

export const DEFAULT_WEAPON_ID = "shortsword";
export const WEAPON_LIST = Object.values(WEAPON_TYPES);

export const getWeapon = (id) => WEAPON_TYPES[id] || WEAPON_TYPES[DEFAULT_WEAPON_ID];

export const weaponColorToInt = (hex) => parseInt(String(hex || "#94a3b8").replace("#", ""), 16);
