/** Feedback Leech — 6★ mythic. Typos heal the boss; below 25% HP typos also hurt the team. */
module.exports = {
  id: "feedback_leech",
  name: "Feedback Leech",
  tagline: "Your mistakes feed it. Enrage turns pain into blood.",
  difficulty: 6,
  maxHP: 900,
  moveSpeed: [82, 110, 148],
  yBase: 110,
  yRange: 45,
  projSpeed: [180, 230, 295],
  typoFeed: { heal: 16 },
  typoEnrage: { hpPct: 0.25, damage: 12, heal: 24 },
  typoBomb: { threshold: 4, damage: 26 },
  attackQueues: [["sick_rain"]],
  attackDurations: {},
  windUps: {},
  fireIntervals: {},
  combatProfile: {
    attacks: [
      { id: "summon_typable_minions", weight: 16 },
      { id: "overcharge_blast",       weight: 14 },
      { id: "sick_rain",              weight: 14 },
      { id: "spore_burst",            weight: 12 },
      { id: "shadow_runes",           weight: 12 },
      { id: "paralyze_typer",         weight: 10 },
      { id: "boss_dash",              weight: 14, minRange: 120 },
      { id: "melee_swipe",            weight: 12, maxRange: 210 },
    ],
    ultimate: { id: "leech_ultimate", triggerHpPct: 0.5, name: "Hemorrhage Pulse" },
  },
};
