/** Omega Null — 10★ apex. Every typing mechanic at once. */
module.exports = {
  id: "omega_null",
  name: "Omega Null",
  tagline: "The final exam. No mistakes. No mercy.",
  difficulty: 10,
  maxHP: 1550,
  moveSpeed: [100, 135, 180],
  yBase: 98,
  yRange: 55,
  projSpeed: [215, 280, 355],
  typoFeed: { heal: 10 },
  typoEnrage: { hpPct: 0.35, damage: 10, heal: 18 },
  typoBomb: { threshold: 3, damage: 32 },
  attackQueues: [["singularity"]],
  attackDurations: {},
  windUps: {},
  fireIntervals: {},
  combatProfile: {
    attacks: [
      { id: "chain_cancel",           weight: 14, chainLength: 3 },
      { id: "safe_zone",              weight: 14, mapDamage: 55 },
      { id: "mirror_word",            weight: 13 },
      { id: "overcharge_blast",       weight: 12, blastDamage: 48 },
      { id: "shield_word",            weight: 12, shieldAmount: 80 },
      { id: "summon_typable_minions", weight: 11 },
      { id: "laser_beam",             weight: 11 },
      { id: "paralyze_typer",         weight: 10 },
      { id: "ruin_pillars",           weight: 10 },
      { id: "tempest",                weight: 9 },
      { id: "singularity",            weight: 8, minRange: 90 },
      { id: "boss_teleport",          weight: 8, minRange: 60 },
    ],
    ultimate: { id: "omega_ultimate", triggerHpPct: 0.35, name: "Null Genesis" },
  },
};
